[package]
name = "jsa8e"
version = "0.1.0"
description = "Atari 800 XL emulator desktop shell"
authors = ["A8E contributors"]
edition = "2021"

[lib]
name = "jsa8e_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
